name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          cache-on-failure: true

      - name: Install Nix
        uses: cachix/install-nix-action@v21

      - name: Doc Tests
        run: |
          nix develop -c cargo test --release --all-features --doc

      - name: Generate Documentation
        run: |
          nix develop -c cargo doc --workspace --no-deps --lib --release
          echo '<meta http-equiv="refresh" content="0; url=relational_graphql">' > target/doc/index.html

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
